# adds E3SM to container with ATS already compiled,
# provides backbone for e3sm testing

FROM metsi/ats:elm_ats-latest

ARG https_proxy=
ARG http_proxy=

USER root

# LANL stuff -- unset proxy
ENV https_proxy= \
    http_proxy=
# end LANL stuff

# ORNL stuff -- corporate certificates
COPY Docker/ca.crt /usr/local/share/ca-certificates/corp-ca.crt
RUN update-ca-certificates
# end ORNL stuff

# add libxml, perl interface for CIME
RUN apt-get -q update -y && apt-get install -y \
    libxml2 \
    libxml2-dev \
    libxml2-utils \
    libxml-libxml-perl \
    subversion \
    csh \
    && apt-get clean all

USER amanzi_user
WORKDIR /home/amanzi_user

# fix the Amanzi installation
RUN cd /home/amanzi_user/install/lib \
    && sed -i -e '4a\if (NOT TARGET netcdf)' -e '11i\endif()' AmanziImportedTargets.cmake

# Add cime directory and files
RUN mkdir -p /home/amanzi_user/.cime
COPY cime_files/* /home/amanzi_user/.cime/

# make work, case, output directories
RUN mkdir -p work/cases \
    && mkdir -p work/output

# get and unpack input data
RUN cd /home/amanzi_user/work \
    && git clone --depth 1 -b compass-glm https://github.com/rfiorella/pt-e3sm-inputdata inputdata \
    && cd inputdata \
    && ./unpack.sh \
    # trim excess data not used in CI or COMPASS
    && rm -rfv /home/amanzi_user/work/inputdata/atm/datm7/CLM1PT_data \
    && rm -rfv /home/amanzi_user/work/inputdata/atm/datm7/atm_forcing.datm7.GSWP3.0.5d.v2.c180716_NGEE-Grid \
    && rm -rfv /home/amanzi_user/work/inputdata/atm/datm7/atm_forcing.datm7.GSWP3.0.5d.v2.c180716_42FLUXNETSITES \
    && rm -rfv /home/amanzi_user/work/inputdata/atm/datm7/GSWP3_daymet \
    && rm -rfv /home/amanzi_user/work/inputdata/atm/datm7/Daymet_ERA5 \
    && rm -rfv /home/amanzi_user/work/inputdata/.git 

# git must be configured for E3SM
RUN git config --global user.email "elmats@dev.null" \
    && git config --global user.name "ELM-ATS Developer"

# set up the environment
ENV CIMEROOT=home/amanzi_user/E3SM/cime \
    PYTHONPATH=/home/amanzi_user/E3SM/cime/scripts/Tools:/home/amanzi_user/E3SM/cime/scripts/lib \
    CIME_MODEL=e3sm \
    AMANZI_DIR=/home/amanzi_user/install/ \
    ATS_DIR=/home/amanzi_user/install/ \
    NETCDF_PATH=/home/amanzi_user/install/tpls \
    HDF5_HOME=/home/amanzi_user/install/tpls \
    HDF5_PATH=/home/amanzi_user/install/tpls 



