# adds E3SM to container with ATS already compiled,
# provides backbone for e3sm testing

#FROM metsi/ats:rfiorella--ats-elm-latest
FROM metsi/ats:master-latest

ARG amanzi_tpls_ver=latest
ARG mpi_flavor=mpich
ARG amanzi_branch=master
ARG ats_branch=
ARG ats_tests_branch=
ARG https_proxy=
ARG http_proxy=

# Set path to make it easier to run amanzi
ENV PATH=/home/amanzi_user/install/bin:${PATH}
RUN echo $PATH

# Create mount point for work on the host
RUN mkdir /home/amanzi_user/work \
    && mkdir /home/amanzi_user/.cime

# Unset proxy
ENV https_proxy= \
    http_proxy=

FROM build-ats AS build-e3sm
# Copy E3SM into container
ADD --chown="amanzi_user:amanzi_user" E3SM /home/amanzi_user/E3SM
COPY --chown="amanzi_user:amanzi_user" cime_files/* /home/amanzi_user/.cime/
ADD --chown="amanzi_user:amanzi_user" scripts/ /home/amanzi_user/scripts

# need a version of python 8 currently for this version of cime
USER root
RUN apt-get -q update -y && apt-get install -y \
    libxml2 \
    libxml2-dev \
    libxml2-utils \
    libxml-libxml-perl \
    subversion \
    csh \
    && apt-get clean all \
    && mv /bin/sh /bin/sh.orig \
    && ln -s /bin/bash /bin/sh \
    # need to make each of these directories explicitly because RUN uses
    # /bin/sh and so brace expansion is not available:
    && cd /home/amanzi_user \
    && mkdir -p work/inputdata \
    && mkdir -p work/cases \
    && mkdir -p work/output \
    && chown -R amanzi_user:amanzi_user work

USER amanzi_user

# ENV CASE_NAME=/home/amanzi_user/work/output/f19_g16.IGSWELMBGC \
#     USER=amanzi_user \
#     CIMEROOT=/home/amanzi_user/E3SM/cime \
#     PYTHONPATH=/home/amanzi_user/E3SM/cime/scripts/Tools:/home/amanzi_user/E3SM/cime/scripts/lib:$PYTHONPATH \
#     CIME_MODEL=e3sm \
#     ATS_DIR=/home/amanzi_user/install/

#  RUN cd /home/amanzi_user/E3SM/cime/scripts \
#      && ./create_newcase --case ${CASE_NAME} --res f19_g16 --compset IGSWELMBGC --mach docker-ats --compiler gnu \
#      && cd ${CASE_NAME} \
#      && ./xmlchange DATM_CLMNCEP_YR_END=1995 \
#      && ./xmlchange PIO_TYPENAME=netcdf \
#      && ./xmlchange RUNDIR=${PWD}/run \
#      && ./xmlchange EXEROOT=${PWD}/bld \
#      && ./xmlchange NTASKS=1 \
#      && ./xmlchange DIN_LOC_ROOT=$PWD \
#      && ./case.setup
# #      && ./case.build
