name: Build Docker Image

on:
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GHA_PAT }}
      - name: Checkout amanzi repository
        run: |
          git clone https://github.com/amanzi/amanzi
      - name: Extract the branch name
        id: branch
        working-directory: amanzi
        run: |
          AMANZI_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "AMANZI_BRANCH=$AMANZI_BRANCH" >> $GITHUB_ENV
      - name: Filter the branch name to generate a tag for Docker
        id: tag
        run:
          echo "AMANZI_BRANCH_TAG=$(echo ${{env.AMANZI_BRANCH}} | sed -e 's/\//--/g')" >> $GITHUB_ENV
      - name: Get TPLs version
        id: version
        working-directory: amanzi/Docker
        run: |
          ls *
          echo "AMANZI_TPLS_VER=$(./get_tpls_version.sh)" >> $GITHUB_ENV
      - name: Output the TPLs version
        run:
          echo "TPLs version = ${{env.AMANZI_TPLS_VER}}"
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker image
        run: docker build --push --build-arg amanzi_branch='master' --build-arg amanzi_tpls_ver=${{env.AMANZI_TPLS_VER}} --build-arg ats_branch='master' --file Docker/Dockerfile-ATS-ELM --tag ${{ secrets.DOCKERHUB_USERNAME }}/compass-elm-ats:latest .
  test:
    needs: build
    name: Run ELM test
    runs-on: ubuntu-latest
    container:
      image: metsi/compass-elm-ats:latest
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - name: deal with weird undocumented HOME issue, cime workaround for GHA runners, and setup input datafiles
        run: |
          echo HOME=/home/amanzi_user >> "$GITHUB_ENV"
          git clone -b compass-glm https://github.com/rfiorella/pt-e3sm-inputdata /home/amanzi_user/inputdata
          cd /home/amanzi_user/inputdata/
          ./unpack.sh
          cd /home/amanzi_user
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GHA_PAT }}
      - name: run test case
        run: |
          export E3SM_WORK_DIR=/home/amanzi_user/work
          export ELM_ATS_SRC_DIR=/home/amanzi_user/E3SM
          export MACHINE_NAME=docker-ats
          export COMPILER_NAME=gnu
          cd $(find / -path '*/oakharbor_column')
          . build_example.sh
